=== bjax/DAVE-ML-Schema/DAVE-ML_intro/Document Type Definitions/DAVEfunc.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- ================================================================ -->
<!--                                                                  -->
<!--               Dynamic Aerospace Vehicle Exchange DTD             -->
<!--                  Function Data Representation                    -->
<!--                                                                  -->
<!--                      $Revision: 1.4 $                            -->
<!--                                                                  -->
<!-- URL: http://dcb.larc.nasa.gov/utils/fltsim/DAVE/DAVEfunc.dtd     -->
<!--                                                                  -->
<!-- Authors:                                                         -->
<!--  E. Bruce Jackson <e.b.jackson@larc.nasa.gov>                    -->
<!--  Bruce L. Hildreth <bruce@pax.saic.com>                          -->
<!--                                                                  -->
<!-- Purpose:                                                         -->
<!--  Proposed standard for exchanging dynamic models of aerospace    -->
<!--  vehicles, including aero, engine, gear, inertia, and control    -->
<!--  models.                                                         -->
<!--                                                                  -->
<!--  This preliminary version defines just function table formats    -->
<!--  typically associated with aerodynamic function data, but can    -->
<!--  be used to describe any non-linear multi-dimensional function.  -->
<!--                                                                  -->
<!-- Status:                                                          -->
<!--  In development. Direct comments to above authors                -->
<!--                                                                  -->
<!-- ================================================================ -->

<!-- ================================================================ -->
<!--                                                                  -->
<!-- Acknowledgement:                                                 -->
<!--   Assistance and encouragement by Jon S. Berndt <jsb@hal-pc.org> -->
<!--   whose JSBsim aero & control law XML format was original work   -->
<!--                                                                  -->
<!-- ================================================================ -->

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                         Level 0 Elements                         -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!-- ================================================================ -->
<!-- Root element is DAVEfunc, composed of a file header element      -->
<!--  followed by 0 or more variable definitions (wiring info), break -->
<!--  point definitions, and function elements.	                      -->
<!-- ================================================================ -->

<!ELEMENT DAVEfunc (fileHeader, variableDef*, 
			 breakpointDef*, function+)>

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                         Level 1 Elements                         -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!-- ================================================================ -->
<!-- The header element requires an author and a creation date;       -->
<!--  optional content are description, references and mod records.   -->
<!-- ================================================================ -->

<!ELEMENT fileHeader (author, fileCreationDate, description?,
                       reference*, modificationRecord*)>

<!-- ================================================================ -->
<!-- variableDef elements provide wiring information - that is, they  -->
<!--  identify the input and output signals used by these function    -->
<!--  blocks. They also provide MathML content markup to indicate any -->
<!--  calculation required to arrive at the value of the variable,    -->
<!--  using other variables as inputs. Note the breakpoint values are -->
<!--  specified separately since one input signal may be normalized   -->
<!--  to more than one breakpoint set (for gridded function data).    -->
<!-- ================================================================ -->

<!ELEMENT variableDef (description?, calculation?, isOutput?)>
<!ATTLIST variableDef
	name            CDATA #REQUIRED
        varID           ID    #REQUIRED
	units           CDATA #REQUIRED
        axisSystem      CDATA #IMPLIED
	sign            CDATA #IMPLIED
	alias           CDATA #IMPLIED
        symbol		CDATA #IMPLIED
	initialValue    CDATA #IMPLIED
>

<!-- ================================================================ -->
<!-- A breakpointDef is where gridded table breakpoints are given.    -->
<!--  Since these are separate from function data, may be reused.     -->
<!-- ================================================================ -->

<!ELEMENT breakpointDef (description?, bpVals)>
<!ATTLIST breakpointDef
        name            CDATA #IMPLIED
        bpID            ID    #REQUIRED
        units           CDATA #IMPLIED
>

<!ELEMENT bpVals (#PCDATA)>

<!-- ================================================================ -->
<!-- Each function has optional description, optional provenance, and -->
<!--  either a simple input/output values or references to more       -->
<!--  complete (possible multiple) input, output, and function data   -->
<!--  elements.                                                       -->
<!-- ================================================================ -->

<!ELEMENT function 
  (
    description?, provenance?, 
      (
        (independentVarPts+, dependentVarPts) | 
        (independentVarRef+, dependentVarRef, functionDefn)
      )
  )
>
<!ATTLIST function
	name     CDATA #REQUIRED
>

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                         Level 2 Elements                         -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!-- ================================================================ -->
<!-- author includes alternate means of indentifying author using     -->
<!-- XNS or normal e-mail/address                                     -->
<!-- ================================================================ -->

<!ELEMENT author (address?)>
<!ATTLIST author    
	name     CDATA #REQUIRED
        org      CDATA #REQUIRED
        xns      CDATA #IMPLIED
>

<!-- ================================================================ -->
<!-- fileCreationDate is simply a string with a date in it.         -->
<!-- ================================================================ -->

<!ELEMENT fileCreationDate EMPTY>
<!ATTLIST fileCreationDate date CDATA #REQUIRED>

<!-- ================================================================ -->
<!-- optional description is free-form text describing something.     -->
<!-- ================================================================ -->

<!ELEMENT description (#PCDATA)>

<!-- ================================================================ -->
<!-- optional isOutput element signals a variable that should be      -->
<!-- forced to be an output, even if it is used as an input elsewhere.-->
<!-- ================================================================ -->

<!ELEMENT isOutput EMPTY>

<!-- ================================================================ -->
<!-- optional calculation element is MathML 2 content markup          -->
<!-- describing how something is calculated.                          -->
<!-- ================================================================ -->
<!ENTITY  % mathml PUBLIC "-//W3C//DTD MathML 2.0//EN"
           "mathml2/mathml2.dtd">
%mathml;
<!ELEMENT calculation (math)>


<!-- ================================================================ -->
<!-- A reference element associates an external document with an ID   -->
<!--  making use of XLink semantics.                                  -->
<!-- ================================================================ -->

<!ELEMENT reference EMPTY>
<!ATTLIST reference 
        xmlns:xlink   CDATA #FIXED 'http://www.w3.org/1999/xlink'
        xlink:type    (simple) #FIXED 'simple'
        refID         ID    #REQUIRED
        author        CDATA #REQUIRED
        title         CDATA #REQUIRED
        accession     CDATA #IMPLIED
        date          CDATA #REQUIRED
        xlink:href    CDATA #IMPLIED
>

<!-- ================================================================ -->
<!-- A modificationRecord associates a modification event with an ID -->
<!-- ================================================================ -->

<!ELEMENT modificationRecord (author, description?)>
<!ATTLIST modificationRecord
        modID        ID    #REQUIRED
        refID        IDREF #IMPLIED
>

<!-- ================================================================ -->
<!-- optional provenance describes history or source of data          -->
<!--  and includes author, date, and zero or more references to       -->
<!--  documents and modification records.                             -->
<!-- ================================================================ -->

<!ELEMENT provenance (author, functionCreationDate, documentRef*, 
                      modificationRef*)>

<!-- ================================================================ -->
<!-- An independentVarPts element is a simple list of breakpoints   -->
<!--  and contains name, units, and sign convention attributes.       -->
<!--  An optional extrapolate attribute describes how to extrapolate  -->
<!--  the output value when the input value exceeds specified values. -->
<!-- ================================================================ -->

<!ELEMENT independentVarPts (#PCDATA)>
<!ATTLIST independentVarPts 
	name  CDATA #IMPLIED
	units CDATA #IMPLIED
	sign  CDATA #IMPLIED
	extrapolate (neither | min | max | both) #IMPLIED
>

<!-- ================================================================ -->
<!-- A dependentVarPts element is a simple of function values       -->
<!--  and contains name, units, and sign convention attributes.       -->
<!--  Data points are arranged as single vector with last-specified   -->
<!--  breakpoint values changing most frequently. Note that the       -->
<!--  number of dependent values must equal the product of the number -->
<!--  of independent values for this simple, gridded, realization.    -->
<!-- ================================================================ -->

<!ELEMENT dependentVarPts (#PCDATA)>
<!ATTLIST dependentVarPts 
	name  CDATA #IMPLIED
	units CDATA #IMPLIED
	sign  CDATA #IMPLIED
>

<!-- ================================================================ -->
<!-- An independentVarRef more fully describes the input mapping    -->
<!--  of the function by pointing to a separate breakpoint definition -->
<!--  element. This allows common breakpoint values for many tables.  -->
<!-- ================================================================ -->

<!ELEMENT independentVarRef EMPTY>
<!ATTLIST independentVarRef
        varID   IDREF #REQUIRED
	min     CDATA #IMPLIED
	max     CDATA #IMPLIED
        extrapolate (neither | min | max | both) #IMPLIED
>

<!-- ================================================================ -->
<!-- A dependentVarRef ties the output of a function to a signal    -->
<!--  name defined previously in a variable definition.               -->
<!-- ================================================================ -->

<!ELEMENT dependentVarRef EMPTY>
<!ATTLIST dependentVarRef varID  IDREF #REQUIRED>

<!-- ================================================================ -->
<!-- A function_defn defines how function is represented in one of    -->
<!--  three possible ways: gridded (implies breakpoints), ungridded   -->
<!--  (with explicit independent values for each point) or a math     -->
<!--  function definition (TBD).                                      -->
<!-- ================================================================ -->

<!ELEMENT functionDefn
  (
    griddedTable | ungriddedTable | mathFunction
  )
>
<!ATTLIST functionDefn name CDATA #IMPLIED>

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                         Level 3 Elements                         -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!ELEMENT address (#PCDATA)>

<!ELEMENT functionCreationDate EMPTY>
<!ATTLIST functionCreationDate date CDATA #REQUIRED>

<!ELEMENT documentRef EMPTY>
<!ATTLIST documentRef docID IDREF #REQUIRED>

<!ELEMENT modificationRef EMPTY>
<!ATTLIST modificationRef modID IDREF #REQUIRED>

<!ELEMENT griddedTable ( breakpointRefs, confidenceBound?, dataTable )>
<!ATTLIST griddedTable name CDATA #IMPLIED>

<!ELEMENT ungriddedTable ( confidenceBound?, dataPoint+)>
<!ATTLIST ungriddedTable name CDATA #IMPLIED>

<!ELEMENT mathFunction EMPTY>	<!-- format TBD -->

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                         Level 4 Elements                         -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!-- ================================================================ -->
<!-- The breakpointRefs elements tie the independent variable names   -->
<!--  for the function to specific breakpoint values defined earlier. -->
<!-- ================================================================ -->
<!ELEMENT breakpointRefs (bpRef+)>

<!-- ================================================================ -->
<!-- The confidenceBound element is used to declare the confidence    -->
<!--  interval associated with the data table. This is a placeholder. -->
<!-- ================================================================ -->

<!ELEMENT confidenceBound EMPTY>
<!ATTLIST confidenceBound value CDATA #REQUIRED>

<!-- ================================================================ -->
<!-- The dataTable element is used by gridded tables where the indep. -->
<!--  variable values are implied by breakpoint sets. Thus, the data  -->
<!--  embedded between the dataTable element tags is expected to be   -->
<!--  sorted ASCII values of the gridded table, wherein the last      -->
<!--  independent variable listed in the function header varies most  -->
<!--  rapidly. Values are comma or whitespace separated values.       -->
<!-- ================================================================ -->

<!ELEMENT dataTable (#PCDATA)>

<!-- ================================================================ -->
<!-- The dataPoint element is used by ungridded tables to list the    -->
<!--  values of independent variables that are associated with each   -->
<!--  value of dependent variable. For example:                       -->
<!--                                                                  -->
<!--  <dataPoint>                                                     -->
<!--    0.1, -4.0, 0.2      <!- Mach, alpha, CL ->                    -->
<!--  </dataPoint>                                                    -->
<!--  <dataPoint>                                                     -->
<!--    0.1,  0.0, 0.6      <!- Mach, alpha  CL ->                    -->
<!--  </dataPoint>                                                    -->
<!--                                                                  -->
<!--  No requirement on ordering of independent variables is implied. -->
<!--   Since this is a ungridded table, the intepreting application   -->
<!--   is required to handle unsorted data.                           -->
<!-- ================================================================ -->

<!ELEMENT dataPoint (#PCDATA)>

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                         Level 5 Elements                         -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!-- ================================================================ -->
<!-- The bpRef element provides references to breakpoint lists so     -->
<!--  breakpoints can be defined separately from, and reused by,      -->
<!--  several data tables.                                            -->
<!-- ================================================================ -->

<!ELEMENT bpRef EMPTY>
<!ATTLIST bpRef bpID IDREF #REQUIRED>

<!-- ================================================================ -->
<!-- ================================================================ -->

=== bjax/DAVE-ML-Schema/DAVE-ML_intro/Examples/twoD_table.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE DAVEfunc SYSTEM "DAVEfunc.dtd">
<DAVEfunc>
  <fileHeader>

      <author name="Bruce Jackson" org="NASA Langley Research Center" xns="@bjax"/>
      <fileCreationDate date="01-MAR-2002"/>
      <description>
	 Coefficient of lift (non-dimensional) - single two-dimensional table.
	 Example file for DAVE function table format. This example is more complex.
      </description>

      <reference refID="REF01" author="Raney, David L." 
	      title="F-19A Basic Aerodynamics Model" 
	      accession="NASA TM-4302" date="July 1992"/>
      <reference refID="REF02" author="Buggati, Richard W."
	      title="F-19A Rotary Aerodynamics Model"
	      accession="NASA TM-4303" date="July 1993"
	      xlink:href="http://dcb.larc.nasa.gov/models/tm4303.pdf"/>
      <reference refID="REF03" author="Aviation Leak &amp; Space Tautology"
	      title="F-19A Falling Short on Design Performance Numbers"
	      accession="Vol. 45, Number 12" date="3-JUL-1993"/>

      <modificationRecord modID="A" refID="REF03">
	<author name="Hildrup, Bruce L." org="SAID Patuxent River">
	  <address>
	    1087 Exploration Parkway Ste 201
	    Lexington Park, MD 20654
	  </address>
	</author>
	<description>
	  Reversed sign on drag term for better performance!
	</description>
      </modificationRecord>

  </fileHeader>

      <!-- ================== -->
      <!--  Input variables   -->
      <!-- ================== -->

  <variableDef name="alpha" varID="ALPHA" units="deg" symbol="#x3B1">
    <description>
       Instantaneous true angle-of-attack, in degrees
    </description>
  </variableDef>

  <variableDef name="Mach" varID="MACH" units="ND" symbol="M"/>

      <!-- ================== -->
      <!--  Output variable   -->
      <!-- ================== -->

  <variableDef name="CL" varID="CL" units="ND" symbol="CL">
    <description>
      Coefficient of lift based on alpha and mach.
    </description>
  </variableDef>

      <!-- ================== -->
      <!--  Breakpoint values -->
      <!-- ================== -->

  <breakpointDef name="alpha" bpID="ALPHA1" units="deg">
      <description>
	 Alpha breakpoints for most basic aero data
      </description>
      <bpVals>
      -4.0, 0., 4.0, 8.0, 12.0, 16.0
      </bpVals>
  </breakpointDef>

  <breakpointDef name="mach" bpID="MACH1" units="ND">
    <bpVals>
      0.0, 0.4, 0.8, 0.9, 0.95, 0.99, 1.00, 1.01, 1.05, 1.2
    </bpVals>
  </breakpointDef>

      <!-- ================== -->
      <!--      Functions     -->
      <!-- ================== -->

  <function name="Basic CL">
    <description>
      Basic coefficient of lift table as a function of Mach and angle of attack
    </description>
    <provenance>
      <author name="Bruce Jackson" org="NASA Langley Research Center" xns="@bjax"/>
      <functionCreationDate date="Jul-1994"/>
      <documentRef refID="REF01"/>
      <documentRef refID="REF02"/>
      <modificationRef modID="A"/>
    </provenance>
    <independentVarRef varID="MACH" min="0.3" max="0.95" extrapolate="max"/>   <!-- Mach breakpoints -->
    <independentVarRef varID="ALPHA" min="0.0" max="15.0" extrapolate="both"/> <!-- Alpha breakpoints -->
    <dependentVarRef varID="CL"/>

    <functionDefn name="CL_FN">
      <griddedTable name="CL_TABLE">
	<breakpointRefs>
	  <bpRef bpID="MACH1"/>
	  <bpRef bpID="ALPHA1"/>
	</breakpointRefs>
	<confidenceBound value="95%"/>
	<dataTable> <!-- Note: last breakpoint changes most rapidly -->
 9.5013e-01   6.1543e-01   5.7891e-02   1.5274e-02   8.3812e-01   1.9343e-01
 2.3114e-01   7.9194e-01   3.5287e-01   7.4679e-01   1.9640e-02   6.8222e-01
 6.0684e-01   9.2181e-01   8.1317e-01   4.4510e-01   6.8128e-01   3.0276e-01
 4.8598e-01   7.3821e-01   9.8613e-03   9.3181e-01   3.7948e-01   5.4167e-01
 8.9130e-01   1.7627e-01   1.3889e-01   4.6599e-01   8.3180e-01   1.5087e-01
 7.6210e-01   4.0571e-01   2.0277e-01   4.1865e-01   5.0281e-01   6.9790e-01
 4.5647e-01   9.3547e-01   1.9872e-01   8.4622e-01   7.0947e-01   3.7837e-01
 1.8504e-02   9.1690e-01   6.0379e-01   5.2515e-01   4.2889e-01   8.6001e-01
 8.2141e-01   4.1027e-01   2.7219e-01   2.0265e-01   3.0462e-01   8.5366e-01
 4.4470e-01   8.9365e-01   1.9881e-01   6.7214e-01   1.8965e-01   5.9356e-01
	</dataTable>
      </griddedTable>
    </functionDefn>
  </function>
</DAVEfunc>

=== bjax/DAVE-ML-Schema/DAVE-ML_intro/Examples/simple_aero.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE DAVEfunc SYSTEM "DAVEfunc.dtd">
<DAVEfunc>
    <fileHeader>
        <author name="Bruce Jackson" org="NASA Langley Research Center" xns="@bjax"/>
        <fileCreationDate date="11-MAR-2002"/>
        <description>
	    Coefficient of lift (non-dimensional) versus angle-of-attack, deg.
	    Example file for DAVE function table format. This example is the simplest version.
	</description>
    </fileHeader>
    <function name="CL">
	<independentVarPts>
	  -4.0, 0., 4.0, 8.0, 12.0, 16.0
	</independentVarPts>
        <dependentVarPts>
	  0.0, 0.2, 0.4, 0.8, 1.0, 1.2
        </dependentVarPts>
    </function>
</DAVEfunc>
